//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public string Hinhthucgiao { get; set; }
        public string Hinhthucthanhtoan { get; set; }
        public int ProductID { get; set; }
        public int UserID { get; set; }
        public Nullable<double> TongTien { get; set; }
        public int MaDonHang { get; set; }
    }
}
