//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Nullable<double> Giatien { get; set; }
        public string Mota { get; set; }
        public string Nhasanxuat { get; set; }
        public int ProductID { get; set; }
        public string TenProduct { get; set; }
    }
}
