//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Diachi { get; set; }
        public string Email { get; set; }
        public string Hoten { get; set; }
        public Nullable<int> Namsinh { get; set; }
        public string Sodienthoai { get; set; }
        public int UserID { get; set; }
    }
}
